language: cpp

sudo: true

# toolchains from:
# * https://github.com/travis-ci/apt-source-whitelist
#   - https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        COMPILER=g++-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.8']
      env:
        COMPILER=clang++-3.8

addons:
  apt: 
    sources:
      - george-edison55-precise-backports
    packages:
      - bash
      - coreutils
      - cmake
      - cmake-data

before_script:
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'
  - which clang++ && clang++ --version || true
  - which g++ && g++ --version || true

install:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install lcov
  - |
    if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    fi
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILE=$COMPILER -DCMAKE_BUILE_TYPE=Release
  - make
  - ./Interpreter/test/InterpreterTest

notifications:
  email: cui@hellolw.com
