language: cpp

sudo: true

# toolchains from:
# * https://github.com/travis-ci/apt-source-whitelist
#   - https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        COMPILER=g++-6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        COMPILER=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        COMPILER=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.8']
      env:
        COMPILER=clang++-3.8

# Not yet available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
#          packages: ['clang-3.9']
#      env:
#        COMPILER=clang++-3.9

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env:
#        COMPILER=clang++

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env:
#        COMPILER=clang++

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env:
#        COMPILER=clang++

addons:
  apt:
    packages:
    - bash
    - coreutils

before_script:
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'
  - which clang++ && clang++ --version || true
  - which g++ && g++ --version || true

install:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install lcov

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILE=$COMPILER -DCMAKE_BUILE_TYPE=Release
  - make
  - ./Interpreter/test/InterpreterTest

notifications:
  email: cui@hellolw.com
